hl.on("hyprland.start", function()
    hl.exec_cmd("rm-hypr-input-capture")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start graphical-session.target")
    hl.exec_cmd("rm-shell-start")
    hl.exec_cmd("dunst")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd([[sh -lc 'agent=/usr/lib/x86_64-linux-gnu/ukui-polkit/polkit-ukui-authentication-agent-1; test ! -x "$agent" || exec "$agent"']])
end)

hl.on("hyprland.shutdown", function()
    hl.exec_cmd("systemctl --user stop graphical-session.target")
end)
