general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    color = rgba(09090dff)
}

input-field {
    monitor =
    size = 360, 56
    outline_thickness = 2
    dots_size = 0.22
    outer_color = rgba(75429fff)
    inner_color = rgba(17141fee)
    font_color = rgba(eeeeF4ff)
    placeholder_text = <span foreground="##a7a4ae">Password</span>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(eeeeF4ff)
    font_size = 72
    font_family = JetBrains Mono
    position = 0, 80
    halign = center
    valign = center
}
